### PR TITLE
Build: Fix linux

### PR DESCRIPTION
**Pull request by jeremy-lunarg**
I believe this is a repeat of 12d6936.

### CODE REVIEW

**Comment by johnkslang** [comment]
If it's the same problem, that turned out to be a GCC bug. Build and test of glslang passed in other Linux environments, because they are not using the buggy version of GCC.

From #879:

> Apparently this is a bug in the GCC headers and is fixed in GCC 5.5.0+:
> https://gcc.gnu.org/PR58265
> https://gcc.gnu.org/git/?p=gcc.git;a=patch;h=5464a27a8faed210695ce5a4ff1133bc415f0d54

But, is this the same problem as that?  It looks a bit different, and precedent for it appears 24 lines later (though it's confusing to use name hiding this way; the other commit used a more explicit name for the nested scope). Thanks.

**Comment by jeremy-lunarg** [comment]
Yep, sorry, I should have posted my output. This is from GCC 5.4.0 (which is also what @EoD noted).

```
[ 35%] Building CXX object glslang/CMakeFiles/glslang.dir/MachineIndependent/SymbolTable.cpp.o
[ 35%] Building CXX object glslang/CMakeFiles/glslang.dir/MachineIndependent/ShaderLang.cpp.o
[ 35%] Building CXX object glslang/CMakeFiles/glslang.dir/MachineIndependent/Scan.cpp.o
[ 36%] Building CXX object glslang/CMakeFiles/glslang.dir/MachineIndependent/ParseHelper.cpp.o
In file included from /home/jeremy/Development/glslang/glslang/MachineIndependent/../Include/../Include/Common.h:99:0,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/../Include/InfoSink.h:38,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/parseVersions.h:42,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.h:47,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.cpp:38:
/usr/include/c++/5/bits/move.h: In instantiation of ‘void std::swap(_Tp&, _Tp&) [with _Tp = glslang::pool_allocator<char>]’:
/usr/include/c++/5/bits/allocator.h:175:8:   required from ‘static void std::__alloc_swap<_Alloc, false>::_S_do_it(_Alloc&, _Alloc&) [with _Alloc = glslang::pool_allocator<char>]’
/usr/include/c++/5/bits/basic_string.tcc:67:50:   required from ‘void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::swap(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = glslang::pool_allocator<char>]’
/usr/include/c++/5/bits/basic_string.h:589:2:   required from ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = glslang::pool_allocator<char>]’
/home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.cpp:1454:27:   required from here
/home/jeremy/Development/glslang/glslang/MachineIndependent/../Include/../Include/PoolAlloc.h:318:21: error: ‘glslang::pool_allocator<T>& glslang::pool_allocator<T>::operator=(const glslang::pool_allocator<T>&) [with T = char]’ is protected
     pool_allocator& operator=(const pool_allocator&) { return *this; }
                     ^
In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/vector:60,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/../Public/ShaderLang.h:43,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/parseVersions.h:41,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.h:47,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.cpp:38:
/usr/include/c++/5/bits/move.h:186:11: error: within this context
       __a = _GLIBCXX_MOVE(__b);
           ^
In file included from /home/jeremy/Development/glslang/glslang/MachineIndependent/../Include/../Include/Common.h:99:0,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/../Include/InfoSink.h:38,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/parseVersions.h:42,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.h:47,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.cpp:38:
/home/jeremy/Development/glslang/glslang/MachineIndependent/../Include/../Include/PoolAlloc.h:318:21: error: ‘glslang::pool_allocator<T>& glslang::pool_allocator<T>::operator=(const glslang::pool_allocator<T>&) [with T = char]’ is protected
     pool_allocator& operator=(const pool_allocator&) { return *this; }
                     ^
In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/vector:60,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/../Public/ShaderLang.h:43,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/parseVersions.h:41,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.h:47,
                 from /home/jeremy/Development/glslang/glslang/MachineIndependent/ParseHelper.cpp:38:
/usr/include/c++/5/bits/move.h:187:11: error: within this context
       __b = _GLIBCXX_MOVE(__tmp);
           ^
glslang/CMakeFiles/glslang.dir/build.make:254: recipe for target 'glslang/CMakeFiles/glslang.dir/MachineIndependent/ParseHelper.cpp.o' failed
make[2]: *** [glslang/CMakeFiles/glslang.dir/MachineIndependent/ParseHelper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/jeremy/Development/glslang/build'
CMakeFiles/Makefile2:1003: recipe for target 'glslang/CMakeFiles/glslang.dir/all' failed
make[1]: *** [glslang/CMakeFiles/glslang.dir/all] Error 2
make[1]: Leaving directory '/home/jeremy/Development/glslang/build'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jeremy-lunarg** [comment]
I can name it `biasFeatureString` or do you have something better in mind? Perhaps @amdrexu can recommend something.

**Comment by johnkslang** [comment]
@jeremy-lunarg that's fine, I don't too much what the name is.

Does that mean the broken GCC installs can't be fixed, that we have to do this in glslang instead?  I imagine this will be an ongoing problem, as there is actually nothing wrong with the code folks are checking in; it's just a bug in one version of GCC.

**Comment by EoD** [comment]
It's actually a bug in the headers GCC provide, not the GCC compiler. Hence also clang and ICC are affected the same way.

Personally, I don't think that this should be fixed in glslang. You could add a warning pragma in the code which gets executed if GCC 5.4.x is being used.

**Comment by jeremy-lunarg** [comment]
> Personally, I don't think that this should be fixed in glslang. You could add a warning pragma in the code which gets executed if GCC 5.4.x is being used.

I tend to agree. Kind of a pain for Ubuntu 16.04 users though. I've not had to switch versions for any thing else thus far.

**Comment by johnkslang** [comment]
Okay, will for "all of the above": pull this one in and expect tools to get fixed so it's not a long-term problem.

**Pull request merged**
