### PR TITLE
Fix variable shadowing warnings.

### PR DESCRIPTION
**Pull request by null77**
These were showing up in a Visual Studio compile.

Also curious if there's a way to enable specific warnings for the Visual Studio build in CMake. These were caught using a different build system.

### CODE REVIEW

**Comment by johnkslang** [comment]
Can you clarify what the actual issue is?

**Comment by null77** [comment]
Sure, variable shadowing: https://en.wikipedia.org/wiki/Variable_shadowing

This was showing up as a compiler warning. I don't have the exact text on hand. It's generally agreed to not be a great programming practice, and can lead to odd situations (ie re-declaring an inner loop variable "i", then needing to access the outer variable).

**Comment by johnkslang** [comment]
This is a key feature of C++ to enable multiple authors to not have to know everything in order to add something.  With the proposed changes now, an author could now modify code accidentally using the more natural original name, and get the one from the wrong scope.

I could see doing something like this is some confusing cases, but would want to more carefully craft the names (e.g., the outer name should be longer and more descriptive than the local name).

**Comment by null77** [comment]
I agree the names aren't great. Unfortunately I won't work on this.

**Pull request closed without merging**
