### PR TITLE
Fix unsized array buffer data size

### PR DESCRIPTION
**Pull request by tsuoranta**
A fix for #1852.

### CODE REVIEW

**Comment by tsuoranta** [comment]
I am examining the test failures related to reflection. While doing this, I noticed that some of the shaders do not meet minimum GL requirements:
GL 4.5 says 14 for MAX_GEOMETRY_UNIFORM_BLOCKS.
Output from my reflection program using OpenGL and minimal fragment shader to match reflection.vert:
```
GL vendor    : Intel Open Source Technology Center
GL renderer  : Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
GL version   : 4.5 (Core Profile) Mesa 19.0.2
GLSL version : 4.50
MAX_COMPUTE_WORK_GROUP_COUNT[0]     = 65535
MAX_COMPUTE_WORK_GROUP_COUNT[1]     = 65535
MAX_COMPUTE_WORK_GROUP_COUNT[2]     = 65535
MAX_COMPUTE_WORK_GROUP_SIZE[0]      = 1792
MAX_COMPUTE_WORK_GROUP_SIZE[1]      = 1792
MAX_COMPUTE_WORK_GROUP_SIZE[2]      = 1792
MAX_COMPUTE_WORK_GROUP_INVOCATIONS  = 1792
MAX_COMPUTE_SHARED_MEMORY_SIZE      = 65536
MAX_VERTEX_UNIFORM_BLOCKS           = 14
MAX_GEOMETRY_UNIFORM_BLOCKS         = 14
MAX_TESS_CONTROL_UNIFORM_BLOCKS     = 14
MAX_TESS_EVALUATION_UNIFORM_BLOCKS  = 14
MAX_FRAGMENT_UNIFORM_BLOCKS         = 14
MAX_COMBINED_UNIFORM_BLOCKS         = 84
Loading GL_VERTEX_SHADER from '/home/timo/git/glslang/Test/reflection.vert'
Loading GL_FRAGMENT_SHADER from '/home/timo/git/glslang/Test/reflection.vert.frag'
Linking program:
Could not link program:
Info Log: '''error: Too many vertex uniform blocks (15/14)
'''
```

**Comment by tsuoranta** [comment]
Here is an example of difference in reflection.vert:
* buf1 size before change = 4
* buf1 size with change = 8
* buf1 Intel driver reports GL_BUFFER_DATA_SIZE = 16
```
buffer buf1 {
    float scalar;
    float runtimeArray[];
} buf1i;
```
OpenGL 7.3.1 says on BUFFER_DATA_SIZE:

>   If the final member of an active shader storage block is an array with no declared size, the minimum buffer size is computed assuming the array was declared as an array with one element.

This is the motivation behind the change, and reason why I believe 4 is wrong for buf1 size. With this change, size 8 comes without applying std140 rule 4. Since buf1 does not have standard layout, I suppose GL driver can return anything >= 8, and in case of my laptop with Intel driver, it seems rounding up with base alignment of a vec4 like std140 rule 4 has been applied.

Other differences (buf2, buf3, buf4) are similar.

**Comment by johnkslang** [comment]
The change is simple and probably okay, but the remaining part is to include the spec. support for the change and test results that show the result of the change.

**Comment by arcady-lunarg** [comment]
This was done as part of PR #2231.

**Pull request closed without merging**
