### PR TITLE
Add SPV_AMD_shader_early_and_late_fragment_tests

### PR DESCRIPTION
**Pull request by AMD-dwang**
Support the new extension: SPV_AMD_shader_early_and_late_fragment_tests.

### CODE REVIEW

**Comment by greg-lunarg** [comment]
Can you please sign the CLA so we can proceed? Thanks!

**Comment by greg-lunarg** [comment]
@AMD-dwang Can you please sign the CLA so we can proceed?

**Comment by AMD-dwang** [comment]
> @AMD-dwang Can you please sign the CLA so we can proceed?

Signed. Thanks.

**Review by greg-lunarg — APPROVED** [review]
LGTM. Thanks for the code.

**Pull request merged**
