### PR TITLE
Remove Unix executable permission from text files

### PR DESCRIPTION
**Pull request by akien-mga**
Listed them with:
```
$ find . -path './.git' -prune -o -name '*.*' -type f | LC_ALL=C xargs ls -l | grep "\-rwx"
-rwxr-xr-x 1 akien akien   2492 Dec 10 10:42 ./.appveyor.yml
-rwxr-xr-x 1 akien akien  12312 Dec 10 10:42 ./README.md
-rwxr-xr-x 1 akien akien 326354 Dec 10 10:46 ./SPIRV/GlslangToSpv.cpp
-rwxr-xr-x 1 akien akien   2453 Dec 10 10:46 ./SPIRV/GlslangToSpv.h
-rwxr-xr-x 1 akien akien  99551 Dec 10 10:46 ./SPIRV/SpvBuilder.cpp
-rwxr-xr-x 1 akien akien   9503 Dec 10 10:46 ./SPIRV/SpvPostProcess.cpp
-rwxr-xr-x 1 akien akien   7322 Dec 10 10:46 ./SPIRV/SpvTools.cpp
-rwxr-xr-x 1 akien akien   2896 Dec 10 10:46 ./SPIRV/SpvTools.h
-rwxr-xr-x 1 akien akien  67071 Dec 10 10:46 ./StandAlone/StandAlone.cpp
-rwxr-xr-x 1 akien akien    189 Dec 10 10:42 ./Test/baseResults/spv.subgroupBallotNeg.comp.out
-rwxr-xr-x 1 akien akien   5513 Dec 10 10:42 ./Test/cppSimple.vert
-rwxr-xr-x 1 akien akien    497 Dec 10 10:42 ./Test/hlsl.pp.expand.frag
-rwxr-xr-x 1 akien akien   1217 Dec 10 10:42 ./Test/hlsl.shift.per-set.frag
-rwxr-xr-x 1 akien akien    975 Dec 10 10:42 ./Test/preprocessor.simple.vert
-rwxr-xr-x 1 akien akien   4192 Dec 10 10:42 ./Test/spv.subgroupBallot.comp
-rwxr-xr-x 1 akien akien   1049 Dec 10 10:42 ./Test/spv.subgroupBallotNeg.comp
-rwxr-xr-x 1 akien akien   8551 Dec 10 10:42 ./Test/validate-shaders.sh
-rwxr-xr-x 1 akien akien  71561 Dec 10 10:46 ./glslang/Include/Types.h
-rwxr-xr-x 1 akien akien  61468 Dec 10 10:46 ./glslang/MachineIndependent/Constant.cpp
-rwxr-xr-x 1 akien akien 349330 Dec 10 10:46 ./glslang/MachineIndependent/ParseHelper.cpp
-rwxr-xr-x 1 akien akien  76441 Dec 10 10:46 ./glslang/MachineIndependent/ShaderLang.cpp
-rwxr-xr-x 1 akien akien  29809 Dec 10 10:46 ./glslang/MachineIndependent/iomapper.cpp
-rwxr-xr-x 1 akien akien  33553 Dec 10 10:46 ./glslang/MachineIndependent/localintermediate.h
-rwxr-xr-x 1 akien akien  48222 Dec 10 10:46 ./glslang/MachineIndependent/preprocessor/Pp.cpp
-rwxr-xr-x 1 akien akien  31652 Dec 10 10:46 ./glslang/Public/ShaderLang.h
-rwxr-xr-x 1 akien akien  21346 Dec 10 10:46 ./gtests/Hlsl.FromFile.cpp
-rwxr-xr-x 1 akien akien  20787 Dec 10 10:46 ./gtests/Spv.FromFile.cpp
-rwxr-xr-x 1 akien akien  31373 Dec 10 10:46 ./gtests/TestFixture.h
-rwxr-xr-x 1 akien akien 425688 Dec 10 10:46 ./hlsl/hlslParseHelper.cpp
-rwxr-xr-x 1 akien akien    501 Dec 10 10:42 ./known_good.json
-rwxr-xr-x 1 akien akien   5114 Dec 10 10:42 ./update_glslang_sources.py
```

I kept the executable bit on the `.py` and `.sh` files.

### CODE REVIEW

**Comment by akien-mga** [comment]
I signed the CLA, but I don't think that this file permissions change is copyrightable anyway, so feel free to do those changes directly.

**Comment by johnkslang** [comment]
What harm is this causing? They seem to naturally show up from Window's systems.

**Comment by akien-mga** [comment]
It doesn't cause harm per se as far as I know. It should not have any impact on workflows using `glslang`.

But it's still a bad practice on Unix that can lead to various mild annoyances:
- packaging tools will issue warnings if any such file end up packaged, as permissions in `/usr` have strict guidelines (0755 for directories, 0644 for files, `root:root` ownership). See e.g. https://src.fedoraproject.org/rpms/glslang/blob/master/f/glslang.spec#_38
This kind of "correctness" checks are found in many packages, and if this can be upstreamed, that's better as downstream packages are less cluttered with arguably not-so-important changes.
- command line tools often show executable files with a different highlight, see e.g. Konsole for this repository:
screenshot_20181210_170455
There's no practical reason for `known_good.json` to appear green and with a star hint when `known_good_khr.json` doesn't. Same for `README.md`, while it *is* relevant to know that the extension-less file `make_revision` is meant to be executed.

There might be other, better reasons that I don't know of though.

Windows does tend to treat everything as executable since NTFS has no notion of Unix permissions, but the Git repository does. I think the `core.filemode` setting of `git config` can be used on Windows to avoid this.

**Comment by johnkslang** [comment]
Yes, I agree with should recommend `core.filemode` for Windows' developers.

**Pull request merged**
