### PR TITLE
Add column to location logs.

### PR DESCRIPTION
**Pull request by antaalt**
The column is never printed to error logs. This commit simply add the column to the log after the line. This is really useful for external linting applications that will locate the error for user.

The issue here is that this might be a breaking change as some external parser might be relying on the log format to work correctly, still I think it should be pushed in order to be used as an efficient linter.

This is solving [this issue](https://github.com/KhronosGroup/glslang/issues/3238)

### CODE REVIEW

**Comment by arcady-lunarg** [comment]
I think this is a good idea in principle, you're almost certainly going to need to update some test results though, and also check that the column numbers are actually valid in those test results, since it's likely nobody's actually checked the column numbers since they were never really visible.

**Comment by antaalt** [comment]
I have checked that the column display is valid using vscode-glsllint and it seems to be working fine

**Review by arcady-lunarg — APPROVED** [review]
This looks good, but it definitely is a bit of a compatibility break. I think it's worth it, but I might let this sit for a bit in case anyone has other thoughts.

**Comment by arcady-lunarg** [comment]
Actually, thinking about this more, is there a way to add this behind an option. Would that work with your use case?

**Comment by antaalt** [comment]
It should be possible yes, I can try to look into it

**Comment by antaalt** [comment]
Here I add an option for this, but right now, all test are based on this option, there should probably be some test that do not use this option

**Review by arcady-lunarg — CHANGES_REQUESTED** [review]
Looks good, though I think I would prefer not to update every single test result and leave your one new test as the test of the error column functionality. Could you remove the passing of the new option from the test fixture (but keep your runtests test, we need that)?

**Comment by antaalt** [comment]
Should be good to go, I tried to add a test for it through fixture, but thought the runtests should be enough.

**Review by arcady-lunarg — APPROVED** [review]
LGTM, thanks for this change and for bearing with me through the review process.

**Pull request merged**
