### PR TITLE
Fix compilation with MSVC 2010

### PR DESCRIPTION
**Pull request by rdb**
As the title states.

### CODE REVIEW

**Comment by johnkslang** [comment]
@steve-lunarg does this break your intent?

**Comment by steve-lunarg** [comment]
No.  It would be slightly less efficient, but not enough to worry about.  Seems OK.

Only if it's not to use emplace() any more, I'd fix the comment just above it which still says this in the revised version:

`// emplace gives back a pair whose .first is an iterator to the item...`

**Comment by johnkslang** [comment]
The other aspect is using `[ ]` instead of `find` changes the tree even if the key is missing. Is this search always going to find it, or is it sometimes missing?

**Comment by johnkslang** [comment]
Nevermind, it looks like it has to find it. @rdb  can you delete the comment and resubmit?

**Comment by rdb** [comment]
Amended with requested change.  Thanks!

**Pull request merged**
