### PR TITLE
Fix UBSAN error with negating 0x8000'0000

### LINKED ISSUE #2652: Undefined behavior with shader including -2147483648
See this clusterfuzz bug for the error report: https://bugs.chromium.org/p/chromium/issues/detail?id=1202390

In short, if the shader contains -2147483648 (note that 2147483648 is 0x80000000), glslang parses it as 0x80000000 that is then negated. When constant folding, UBSAN complains about negating this value.

The lexer should have probably just parsed -2147483648 as one signed number.

### PR DESCRIPTION
**Pull request by ShabbyX**
Fixes #2652 

Signed-off-by: Shahbaz Youssefi <ShabbyX@gmail.com>

### CODE REVIEW

**Comment by ShabbyX** [comment]
@greg-lunarg I went ahead and fix this

**Comment by ShabbyX** [comment]
The failure seems like an unrelated flake

**Comment by greg-lunarg** [comment]
Agree. If you git commit --amend the top commit without making any changes and repush (force?) the branch it will retrigger the CI.

**Review by greg-lunarg — APPROVED** [review]
LGTM. This needs no test since there is no functional change.

**Pull request merged**
