### PR TITLE
enable ARB_cull_distance extension

### PR DESCRIPTION
**Pull request by ShchchowAMD**
GLSL Version : >= 130

Purpose:
Allow users to use features by enabling this extension, even in low versions.

Extension Name:
ARB_cull_distance

Builtin-variables:
gl_CullDistance[]

Builtin-functions:
Nah

Keywords:
Double

Features:
Enable gl_CullDistance[] from version 130 where ARB_cull_distance are introduced. Add array size check and relate this array with gl_in and gl_out.

Reference:
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_cull_distance.txt

### CODE REVIEW

**Comment by ShchchowAMD** [comment]
issues with clip/cull distance will be fixed together in next PR.

**Comment by ZhiqianXia** [comment]
@ShchchowAMD Do you want to submit this feature ? I also met the issue.  thanks.

**Comment by ShchchowAMD** [comment]
@ZhiqianXia Let me check my local PRs. Would generate new PRs in several days. This PR may be far behind latest build, let me double check it. I'd let you know this or next week.

**Comment by ZhiqianXia** [comment]
thanks.
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
