### PR TITLE
Emit debug info for accelerationStructure and rayQuery variables.

### PR DESCRIPTION
**Pull request by sajjadmirzanv**
A minor quirk is that multiple source types will get mapped to the same debug type, for example both accelerationStructureNV and accelerationStructureEXT are just named accelerationStructure. But I expect a shader author won't use both extensions in the same program, they'll just pick one, so this should be OK.

### CODE REVIEW

**Comment by arcady-lunarg** [comment]
In the underlying SPIR-V `OpTypeAccelerationStructureNV` and `OpTypeAccelerationStructureKHR` have the same opcode, so it's kind of hard to avoid conflating them into just one type.

**Review by arcady-lunarg — CHANGES_REQUESTED** [review]
Could you add a test for this? The change itself looks fine and isn't doing a lot, just adding an empty struct for the acceleration structure so the test should be fairly trivial to write.

**Comment by sajjadmirzanv** [comment]
Added a test case (copy of an existing one, rayQuery.rgen)

**Review by arcady-lunarg — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
