### PR TITLE
Enable adding capability: MultiViewport

### PR DESCRIPTION
**Pull request by Qining**
Fix issue https://github.com/KhronosGroup/glslang/issues/191

### CODE REVIEW

**Comment by johnkslang** [comment]
Does this have any effect on test results?

**Comment by Qining** [comment]
Just fixed the issue #191. I didn't any difference on other tests. But still, I didn't run the compiled spirv code, just built the tests and validated the generated code.

**Comment by johnkslang** [comment]
The regression test ```spv.420.geom``` uses ```gl_ViewportIndex``` and should show this change.  We need to make the changes together, so the test results match the code base.

**Comment by Qining** [comment]
Oops, sorry, I just tested with Vulkan-CTS's tests. Just updated with commit be4f52a which adds MultiViewport declaration in spv.420.geom.out.

**Pull request merged**
