### PR TITLE
Respect CMAKE_INSTALL_LIBDIR in installed CMake files

### LINKED ISSUE #1965: ${CMAKE_INSTALL_LIBDIR} not respected for cmake files
glslang installs cmake-generated files in hardcoded lib/cmake directory (usually /usr/lib/cmake) without respecting ${CMAKE_INSTALL_LIBDIR}.

Fix: [glslang.patch.txt](https://github.com/KhronosGroup/glslang/files/3812954/glslang.patch.txt)

### PR DESCRIPTION
**Pull request by mattst88**
Fixes #1965

### CODE REVIEW

**Comment by Oxalin** [comment]
Could you have a look at this comment from issue 1965. https://github.com/KhronosGroup/glslang/issues/1965#issuecomment-555606605

**Comment by mattst88** [comment]
I would suggest that you file a separate pull request. I'm already submitting this patch on behalf of someone else...

**Comment by johnkslang** [comment]
Will this move the location of any libraries from where existing consumers might be expecting them?

**Comment by Oxalin** [comment]
@johnkslang : no.

**Pull request merged**
