### PR TITLE
Update spirv tools

### PR DESCRIPTION
**Pull request by alan-baker**
Updates the known good SPIRV-Tools commit and known test failures (see #2053).

### CODE REVIEW

**Comment by johnkslang** [comment]
@jeffbolznv, how is recursiveness supposed to be handled?  The GLSL is:

```
layout(buffer_reference) buffer T1;
layout(set = 3, binding = 1, buffer_reference) buffer T1 {
   layout(offset = 0) int a[2]; // stride = 4 for std430, 16 for std140
   layout(offset = 32) int b;
   layout(offset = 48) T1  c[2]; // stride = 8 for std430, 16 for std140
   layout(offset = 80) T1  d;
} x;
```

And the SPIR-V makes a forward reference to an array (SPIR-V only allows to a struct), as well as making two copies of the struct:

```
               6:             TypeInt 32 1
               9:      6(int) Constant 0
              10:             TypeInt 32 0
              11:     10(int) Constant 2
              12:             TypeArray 6(int) 11
                              TypeForwardPointer 13 PhysicalStorageBufferEXT
              14:             TypeArray 13 11
          15(T1):             TypeStruct 12 6(int) 14 13
              16:             TypeArray 6(int) 11
              17:             TypeArray 13 11
          18(T1):             TypeStruct 16 6(int) 17 13
              13:             TypePointer PhysicalStorageBufferEXT 18(T1)
              19:             TypeArray 13(ptr) 11
              20:             TypePointer StorageBuffer 15(T1)
```

**Comment by johnkslang** [comment]
Well, I no longer see a forward reference to an array, but that's what the change says it addresses, so I'm not sure now.

**Comment by johnkslang** [comment]
I think the issue is that the specification was for a struct pointing to its own type, but that needs to be generalized to allowing a struct containing an array of pointers to the struct's type, so maybe this should be a specification change, not a validator change.

**Comment by jeffbolznv** [comment]
This seems related to https://gitlab.khronos.org/spirv/SPIR-V/issues/394 which is still open. At first glance I don't see what's wrong with the SPIR-V quoted above (the duplicate structure is unexpected, but not invalid). Is there more info somewhere on why it's considered invalid?

**Comment by johnkslang** [comment]
SPIR-V says 

>  Subsequent OpTypeStruct instructions can use Pointer Type as an operand.

Maybe that gets interpreted as "only a structure can consume the forward-declared pointer", but it doesn't really restrict to that because it says "can" not "must/only".  But, in the GLSL, the structure contains an array of the structure, making the forward-declared pointer consumed by an OpTypeArray, which I now suspect the spec should allow.

**Comment by jeffbolznv** [comment]
That's part of what's covered in https://gitlab.khronos.org/spirv/SPIR-V/issues/394. I think this rule probably ought to be disabled until that spec issue is resolved.

**Comment by alan-baker** [comment]
https://github.com/KhronosGroup/SPIRV-Tools/pull/3131

**Comment by johnkslang** [comment]
Khronos has decided to allow extra levels of indirection between the forward-declared pointer and the consumption in the struct, which allows glslang's current behavior as being valid.

**Pull request closed without merging**
