### PR TITLE
cmake: only install public headers

### PR DESCRIPTION
**Pull request by arcady-lunarg**
Only the headers that are part of glslang's public interface are installed. Previously, all of its headers were installed, which exposed a lot of internal implementation details and made it difficult to maintain backward compatiblity. This reduces the API surface somewhat and will make it easier to maintain API and ABI compatibility.

This PR also makes some changes to header files to remove dependencies on things outside the "public API" set listed in #3320. The only exception not on that list but still used is `SPIRV/spirv.hpp`.

### CODE REVIEW

**Comment by arcady-lunarg** [comment]
cc: @juan-lunarg because this involves some changes to the cmakelists but the changes are pretty straightforward.

**Review by juan-lunarg — APPROVED** [review]

**Comment by juan-lunarg** [comment]
As a sanity check I ran the installation locally and grepped for header files. Does this look like you expect?

```
juan@pop-os:~/projects/glslang$ cmake --install build --prefix /tmp | grep .h
-- Up-to-date: /tmp/lib/libSPIRV-Tools-shared.so
-- Up-to-date: /tmp/bin/spirv-lesspipe.sh
-- Up-to-date: /tmp/include/spirv-tools/libspirv.h
-- Up-to-date: /tmp/include/spirv-tools/libspirv.hpp
-- Up-to-date: /tmp/include/spirv-tools/optimizer.hpp
-- Up-to-date: /tmp/include/spirv-tools/linker.hpp
-- Up-to-date: /tmp/include/spirv-tools/instrument.hpp
-- Up-to-date: /tmp/lib/pkgconfig/SPIRV-Tools-shared.pc
-- Up-to-date: /tmp/lib/libMachineIndependent.a
-- Up-to-date: /tmp/include/glslang/Public/ResourceLimits.h
-- Up-to-date: /tmp/include/glslang/Public/ShaderLang.h
-- Up-to-date: /tmp/include/glslang/Public/resource_limits_c.h
-- Up-to-date: /tmp/include/glslang/Include/glslang_c_interface.h
-- Up-to-date: /tmp/include/glslang/Include/glslang_c_shader_types.h
-- Up-to-date: /tmp/include/glslang/Include/ResourceLimits.h
-- Up-to-date: /tmp/include/glslang/MachineIndependent/Versions.h
-- Up-to-date: /tmp/include/glslang/build_info.h
CMake Error: failed to create symbolic link 'glslangValidator': Permission denied
-- Up-to-date: /tmp/include/glslang/SPIRV/GlslangToSpv.h
-- Up-to-date: /tmp/include/glslang/SPIRV/disassemble.h
-- Up-to-date: /tmp/include/glslang/SPIRV/Logger.h
-- Up-to-date: /tmp/include/glslang/SPIRV/spirv.hpp
-- Up-to-date: /tmp/include/glslang/SPIRV/SPVRemapper.h
```

**Comment by juan-lunarg** [comment]
I verified this works by testing against the validation layers. The only thing I had to was remove a single header file:

```
--- a/tests/framework/shader_helper.h
+++ b/tests/framework/shader_helper.h
@@ -18,7 +18,6 @@
 
 #pragma once
 
-#include "glslang/SPIRV/GLSL.std.450.h"
 #include "spirv-tools/libspirv.h"
 #include "glslang/Public/ShaderLang.h"
```

Since everything still compiled we weren't even using this header file 💯

**Comment by juan-lunarg** [comment]
I also just checked the header files being installed and it looks good to me. VVL integration testing looks good to me 👍🏾

**Pull request merged**
