### PR TITLE
add possibility to not override runtime of MSVC

### PR DESCRIPTION
**Pull request by AndreyMlashkin**
Sometimes projects, that are using glslang want to override CMAKE_CXX_FLAGS_RELEASE/CMAKE_CXX_FLAGS_DEBUG on their own. I have introduced a flag to give such possibility

### CODE REVIEW

**Comment by AndreyMlashkin** [comment]
@greg-lunarg , could you  please restart the CI? I think it failed because I have force pushed, when another pipeline was running

**Comment by greg-lunarg** [comment]
@AndreyMlashkin If you run git commit --amend on your local branch without making any changes and repush your branch it will restart CI.

**Comment by AndreyMlashkin** [comment]
This flag is needed, if glslang is included in a big project, that does not manage msvc runtime or has different rules for it.

**Comment by AndreyMlashkin** [comment]
@greg-lunarg , please review

**Comment by greg-lunarg** [comment]
Sorry. Just got back from vacation.

Sorry I didn't see this sooner: could you please fix the indent on the option command?

Otherwise I am fine with this.

**Pull request merged**
