### PR TITLE
Updated cmake to better organize folders and options.

### PR DESCRIPTION
**Pull request by AWoloszyn**
This adds solution folders that properly group gtest/glslang/hlsl.
This also marks gtest options as advanced so they don't show up
in cmake-gui by default.

### CODE REVIEW

**Comment by johnkslang** [comment]
Removing my build directory, and starting fresh, I get this from CMake:

```
CMake Error at External/CMakeLists.txt:20 (set_property):
  set_property could not find TARGET gtest.  Perhaps it has not yet been
  created.


CMake Error at External/CMakeLists.txt:20 (set_property):
  set_property could not find TARGET gtest_main.  Perhaps it has not yet been
  created.


CMake Error at External/CMakeLists.txt:20 (set_property):
  set_property could not find TARGET gmock.  Perhaps it has not yet been
  created.


CMake Error at External/CMakeLists.txt:20 (set_property):
  set_property could not find TARGET gmock_main.  Perhaps it has not yet been
  created.
```

**Comment by AWoloszyn** [comment]
That seems very odd, it looks like you HAVE a folder (external/googletest) but it is empty? Or the gtest libraries are not being created.
The easiest solution to prevent this from ever being in the problem in future is to turn 
```
foreach(target ${GTEST_TARGETS})
   set_property(TARGET ${target} PROPERTY FOLDER gtest)
endforeach()
```
into
```
foreach(target ${GTEST_TARGETS})
  if(TARGET ${target})  
    set_property(TARGET ${target} PROPERTY FOLDER gtest)
  endif()
endforeach()
```

**Comment by johnkslang** [comment]
I have the folder, but it is not empty:

```
$ ls External/
CMakeLists.txt  googletest

john@fanless ~/glslang
$ ls External/googletest/
CMakeLists.txt  googlemock  googletest  README.md  travis.sh
```

I'm not quite seeing what's supposed to line up with what though.

**Comment by johnkslang** [comment]
Update: Deleting everything (build and External) and trying again (including cloning gtest), I didn't see the failures, but I also didn't get gtests built or executing (silent fail).

**Comment by AWoloszyn** [comment]
Your folder structure looks correct but for completeness mine is below.
I tested using both cmake command-line as well as cmake-gui (both in a subdirectory of glslang, and a totally unrelated directory). 
During configure you should see ```Google Mock found - building tests```
If you see ```"Google Mock was not found - tests based on that will not build``` that means External/googletest/CMakeLists.txt could not be found.

```
+---External
|   \---googletest
|       +---googlemock
|       |   +---build-aux
|       |   +---docs
|       |   |   +---v1_5
|       |   |   +---v1_6
|       |   |   \---v1_7
|       |   +---include
|       |   |   \---gmock
|       |   |       \---internal
|       |   |           \---custom
|       |   +---make
|       |   +---msvc
|       |   |   +---2005
|       |   |   \---2010
|       |   +---scripts
|       |   |   \---generator
|       |   |       \---cpp
|       |   +---src
|       |   \---test
|       \---googletest
|           +---build-aux
|           +---cmake
|           +---codegear
|           +---docs
|           +---include
|           |   \---gtest
|           |       \---internal
|           |           \---custom
|           +---m4
|           +---make
|           +---msvc
|           +---samples
|           +---scripts
|           |   \---test
|           +---src
|           +---test
|           \---xcode
|               +---Config
|               +---gtest.xcodeproj
|               +---Resources
|               +---Samples
|               |   \---FrameworkSample
|               |       \---WidgetFramework.xcodeproj
|               \---Scripts
+---glslang
|   +---GenericCodeGen
|   +---Include
|   +---MachineIndependent
|   |   \---preprocessor
|   +---OSDependent
|   |   +---Unix
|   |   \---Windows
|   \---Public
+---gtests
+---hlsl
+---OGLCompilersDLL
+---SPIRV
+---StandAlone
\---Test
    \---baseResults
```

**Comment by johnkslang** [comment]
Thanks @AWoloszyn, I got it working.

**Pull request merged**
