### PR TITLE
Update SPIRV-Tools to version with ray tracing builtin validation

### PR DESCRIPTION
**Pull request by dgkoch**

### CODE REVIEW

**Comment by dgkoch** [comment]
cc @johnkslang - I don't know if the Travis CI is stuck or something?

**Comment by dgkoch** [comment]
@dneto0 clang build on linux is encountering the same  issue that I did on my mac with googletest: 

```
/home/travis/build/KhronosGroup/glslang/External/googletest/googlemock/include/gmock/gmock-actions.h:1523:31: error: default initialization of an object of const type 'const testing::internal::ExcessiveArg' without a user-provided default constructor
    static const ExcessiveArg kExcessArg;
                              ^
/home/travis/build/KhronosGroup/glslang/External/googletest/googlemock/include/gmock/gmock-actions.h:1523:41: note: add an explicit initializer to initialize 'kExcessArg'
    static const ExcessiveArg kExcessArg;
                                        ^
                                        {}
```

**Comment by dgkoch** [comment]
Abandoning in favour of #2473 which has an even newer SPIRV-Tools commit.

**Review by MBNwaiser — COMMENTED** [review]
The first one I was able to do

**Pull request closed without merging**
