### PR TITLE
Iomapper api cleanup

### LINKED ISSUE #3681: Change to CMake install rule for the include directory?
It seems like there are lots of missing headers in the install/include directory now. For example MachineIndependent seems to only come with Versions.h now, and is missing other useful headers such as iomapper.h.
SPIRV is missing SpvTools.h is another example of a useful header that's no longer copied.
Is there a new workflow to follow?

### PR DESCRIPTION
**Pull request by arcady-lunarg**
Clean up iomapper.h to make it suitable as a public API

Remove the dependency on LiveTraverser.h, which transitively includes localintermediate.h. As a result, some things have been moved from iomapper.h to iomapper.cpp, specifically the TVarEntry type and the constructor and destructor of TGlslIoMapper.

Add MachineIndependent/iomapper.h to the list of installed headers.

Fixes #3681

### CODE REVIEW

**Comment by arcady-lunarg** [comment]
In the process of developing this, it turned out that there is a pre-existing array overrun bug that was not getting caught by the address sanitizer. I'm going to fix that before I merge this.

**Review by jeremy-lunarg — APPROVED** [review]
LGTM

**Comment by mbechard** [comment]
This doesn't seem complete yet, as there are many types in iomapper.h that the includer doesn't have definitions for, such as TType, TString, TLayoutPacking, TStorageQualifier etc.

**Comment by mbechard** [comment]
Also need access to `SpvVersion` that `TIntermediate` has an accessor for via `getSpv()`, for use in `glslang::MapToSpirvToolsEnv`. Possibly this should be held in the `TProgram`, to avoid needing to expose TIntermediate as anything more than an opaque type.

**Pull request merged**
