### PR TITLE
Make GL_KHR_ray_query provide EOpConstructAccStruct

### PR DESCRIPTION
**Pull request by thoave-arm**
Previously, GL_KHR_ray_tracing was a required extension to generate
OpConvertUToAccelerationStructureKHR conversion instructions from uint64
and uvec2. However, both GL_KHR_ray_tracing and GL_KHR_ray_query should
provide this construction.

### CODE REVIEW

**Comment by thoave** [comment]
@greg-lunarg apologies for the ping, but I cannot seem to figure out how to add a reviewer to pull requests, can this perhaps only be done by maintainers?

**Comment by greg-lunarg** [comment]
My apologies. Somehow I missed this coming in. Its on my radar now.

**Review by greg-lunarg — CHANGES_REQUESTED** [review]
Can you please add a small test that verifies this capability?

**Comment by thoave-arm** [comment]
@greg-lunarg I've added a small test that verifies that OpConvertUToAccelerationStructureKHR is now available with only GL_KHR_ray_query.

**Review by greg-lunarg — APPROVED** [review]
LGTM. Thanks for the code!

**Pull request merged**
