### PR TITLE
SPV: The result type of OpArrayLength should be UINT

### PR DESCRIPTION
**Pull request by amdrexu**

### CODE REVIEW

**Comment by amdrexu** [comment]
In SPIR-V, it says: OpArrayLength, Result Type must be an OpTypeInt with 32-bit Width and 0 Signedness.

**Comment by johnkslang** [comment]
Since this changes the way existing code in generated, we need to bump up the generator number.

Add a line to:

```
// For low-order part of the generator's magic number. Bump up
// when there is a change in the style (e.g., if SSA form changes,
// or a different instruction sequence to do something gets used).
int GetSpirvGeneratorVersion()
{
    // return 1; // start
    // return 2; // EOpAtomicCounterDecrement gets a post decrement, to map between GLSL -> SPIR-V
    // return 3; // change/correct barrier-instruction operands, to match memory model group decisions
       return 4; // some deeper access chains: for dynamic vector component, and local Boolean component
}
```

Something like


```
return 5; // make OpArrayLength result type be an int with signedness of 0
```

**Comment by amdrexu** [comment]
Thank you. I make a update. The test result files are changed as well and the amount seems large :)

**Comment by johnkslang** [comment]
Yes, now I think I should do this as an independent commit.

I think you forgot to update a few tests, but I'll try doing all this locally.

**Comment by amdrexu** [comment]
Thanks for your kind help.

**Comment by johnkslang** [comment]
This was reverted by ac3707921ed313eaba1c206e8113b85fef054c34.

Sorry about this, but the fix seems incomplete, as it can move the type issue to the subsequent instruction. It may need to be combined with an OpBitCast.

**Pull request merged**
