### PR TITLE
Add setter for TInterimSelection.condition

### PR DESCRIPTION
**Pull request by Drigax**
As titled, this PR adds a setter for TInterimSelection.condition.

### CODE REVIEW

**Comment by Drigax** [comment]
@greg-lunarg can you take a look when you get the time? :)

**Comment by greg-lunarg** [comment]
This looks fine to me. I think the CI problems are due to the fact that your branch is very old. That is almost assuredly the problem with ubuntu-clang-gn. Can you rebase your change onto the latest master and push the new branch?

Not quite sure what is going on with the kokoro license thing. Hopefully it will also clear up with the retrigger.

**Review by greg-lunarg — COMMENTED** [review]
LGTM.

**Comment by Drigax** [comment]
Thanks! CI looks good :)

**Pull request merged**
