### PR TITLE
Also do link tests in the GTest framework

### PR DESCRIPTION
**Pull request by antiagainst**
This PR is another step towards deprecating `runtests`.

Related to #279: I'm leaning towards to use `TOption` like bitmask now.

### CODE REVIEW

**Comment by johnkslang** [comment]
This is good to have the gtest path have this ability.

However, I'm not sure it is yet good to take it out of the runtest.  I suspect there are many places (including the recently added bots to this repository) that are using runtest to verify things are okay, and this dilutes that.

Can we start by having tests in both places?  Maybe with time we can reduce the amount in runtests, but it is an almost free way to do sanity checks in places that have not pulled in gtests, so it might be good to have a (smaller) mix of tests there for some time.

**Comment by johnkslang** [comment]
The removal part is somewhat a duplicate of pull request #267, which it is checked off that submitters have generally switch to using gtests.  How do we know that?

**Comment by antiagainst** [comment]
@johnkslang, ah, that's accidentally checked. Just wanted to remove the [WIP] tag... Will remove the tick.

I'm OK to keep the `runtests` code segment for this. Will revise.

**Comment by antiagainst** [comment]
Done. ;)

**Pull request merged**
