### PR TITLE
Use newer gtest API, replacing deprecated one

### PR DESCRIPTION
**Pull request by dneto0**
Use INSTANTIATE_TEST_SUITE_P instead of
deprecated INSTANTIATE_TEST_CASE_P.

This transition has been going on for about a year,
and this is a good time to change.

### CODE REVIEW

**Comment by dneto0** [comment]
The deprecation is noted here: https://github.com/google/googletest/blob/master/googletest/include/gtest/gtest-param-test.h#L503

Git blame shows the new API has been available for 12 months. https://github.com/google/googletest/blame/master/googletest/include/gtest/gtest-param-test.h#L506

**Comment by johnkslang** [comment]
Agreed this fix is overdue.  The bot failure looks genuine though.

**Comment by johnkslang** [comment]
Maybe things are getting done out of order.

We still advise to use the Sept. 2018 gtests due to compatibility issues.

I think the steps needed are:

1. get everyone off 2013 -> 2015 (includes one of my systems, not all, as the test of still supporting 2013)
1. decide what new known-good of the gtests to use
1. update advice scripts with result of step 2
1. make the changes in this PR

**Comment by johnkslang** [comment]
> The deprecation is noted here:...

But that is added in a later release that the one we've locked onto for glslang.  (In the README and in appveyor.yml.)

If we can now drop 2013 finally, I'm agree adapting to the later versions.

This is just an explanation for why we don't see the deprecated assert.

**Comment by johnkslang** [comment]
I checked the past issues about this.  The last I see, following discussions during 2018 is confirmation (in Feb. and in Nov.) that visual studio 2013 is still supported.

There was some talk of 5 years availability of tools before deprecation.  For visual studio 2015, that will be July this year.  Should we propose (in a separate issue) dropping 2013 support in July 2020?

**Comment by dneto0** [comment]
Ah.  That explains my sense of deja vu.  Sorry to make you go thorugh that analysis again.

**Comment by dneto0** [comment]
I believe this is not urgent from end.

**Comment by johnkslang** [comment]
Closing as superseded by #2365, which is also a bit more comprehensive.

**Pull request closed without merging**
