### PR TITLE
Add Vulkan 1.4 target and client

### PR DESCRIPTION
**Pull request by dneto0**

### CODE REVIEW

**Comment by dneto0** [comment]
Vulkan 1.4 has been released. https://www.khronos.org/news/press/khronos-streamlines-development-and-deployment-of-gpu-accelerated-applications-with-vulkan-1.4

**Review by jeremy-lunarg — APPROVED** [review]
LGTM. Thanks @dneto0

**Comment by iMichka** [comment]
Hello. While building `glslang 15.1.0` in Homebrew, we have hit the following error:

```
 /tmp/glslang-20241213-4591-ojwgqr/glslang-15.1.0/SPIRV/SpvTools.cpp:75:32: error: ‘SPV_ENV_VULKAN_1_4’ is not a member of ‘spv_target_env’
     75 |         return spv_target_env::SPV_ENV_VULKAN_1_4;
        |                                ^~~~~~~~~~~~~~~~~~
  [ 84%] Building CXX object glslang/CMakeFiles/glslang.dir/__/SPIRV/disassemble.cpp.o
```

Maybe you can help us out? Should we raise a separate issue?

**Comment by arcady-lunarg** [comment]
@iMichka, and anyone who has the same problem, make sure you've updated your SPIRV-Headers version using `update_glslang_sources.py`

**Pull request merged**
