### PR TITLE
Add support for GL_EXT_shader_image_int64

### PR DESCRIPTION
**Pull request by Tobski**
This depends on https://github.com/KhronosGroup/SPIRV-Headers/pull/170 and https://github.com/KhronosGroup/SPIRV-Tools/pull/3852 landing first.

### CODE REVIEW

**Comment by johnkslang** [comment]
@Tobski can you rebase this and resubmit?  (I can't even pull this onto a new branch to locally resolve the conflicts; somehow fast-forwarding on a fresh branch is not possible.)

**Comment by Tobski** [comment]
@johnkslang ok - rebased and pushed.. hopefully CI will all pass with a clean bill of health...

**Comment by Tobski** [comment]
Just as an FYI, whilst i'm trying to fix the issues, when the CI-ubuntu-clang-gn build fails, the "Details" link changes to this:

> http://fusion/runanalysis/info/prod%3Agraphics_shader_compiler%2Fglslang%2Flinux-clang-gn%2Fpresubmit/prod%3Agraphics_shader_compiler%2Fglslang%2Flinux-clang-gn%2Fpresubmit/KOKORO/b178d408-c1af-4646-b771-b7033f8bc208/0/prod%3Agraphics_shader_compiler%2Fglslang%2Flinux-clang-gn%2Fpresubmit/Targets

which... what? I'm assuming it's an issue with Kokoro since it's allegedly in Beta but... that's pretty weird. It certainly doesn't give me any information about what failed :(

**Comment by Tobski** [comment]
I've resorted to force-pushing a vague commit message change so I can grab the link before it fails, which for posterity, is this: https://source.cloud.google.com/results/invocations/7e73d117-3749-4fff-927f-b3a176bd0b8f

**Comment by Tobski** [comment]
Ok so it looks like the CI check itself is failing for some reason - it's nothing to do with my PR. Every other test is passing, so not sure what to do about that...

**Comment by Tobski** [comment]
Oh wait there might be some actual errors in there... it's just popped up with a log that wasn't there before. Let me try that again...

**Comment by Tobski** [comment]
@ShchchowAMD it looks like your latest commit to master has introduced some errors - can you please fix these? See https://source.cloud.google.com/results/invocations/7e73d117-3749-4fff-927f-b3a176bd0b8f for details.

**Comment by ShchchowAMD** [comment]
Ok, I'll handle this.

**Comment by johnkslang** [comment]
We definitely have a problem with getting different subsets of tests running at different times, sometimes making it appear everything is okay when it is not, or visa versa.

Letting this one in, assuming will get the same orthogonal failure, which will get fixed shortly.

**Pull request merged**
