### PR TITLE
WIP: SPIRV remapper: allow 64 bit literals in OperandVariableLiteralI…

### PR DESCRIPTION
**Pull request by steve-lunarg**
Removed in favor of #471, which is the same code re-submitted to try to shake the Travis-CI build loose.

### CODE REVIEW

**Comment by steve-lunarg** [comment]
Hmm... the "Travis CI" build has been pending for 6 hours now.  I've seen something similar before, always with the Apple build, which seems to be the case again here.  In the details page, it looks like it hasn't even started trying yet:

> Hang tight, the log cannot be shown until the build has started.

**Comment by johnkslang** [comment]
Looks like it just timed out.  This is labeled as WIP, is there something that is blocked on (getting input from folks)?

If it looks solid, we could try pulling it into master and see if the hang is random or correlated.

**Comment by steve-lunarg** [comment]
Last time I saw this problem I created another branch from scratch with the same code, submitted that, and all was well.  I don't know that it was a "fix" rather than a coincidence (perhaps the build system becoming happy for some other reason), but still, I'm inclined to try for a successful Travis CI.  Unless there's some urgency, I'll submit it again tomorrow.  Maybe either another day or another git branch will make it happy.

Curiously, the build log on the details page for the failing Apple builds looks completely empty for me.  Last time this happened, it showed an internal git error of some sort.

**Comment by johnkslang** [comment]
Will pull when you remove your "WIP".

**Comment by dneto0** [comment]
This patch is compatible with the Vulkan CTS shaders, with SPIR-V validation turned on.  So works for me, but moreso than last time.  :-)

**Pull request closed without merging**
