### PR TITLE
Update SPIRV-Tools: Relaxed checks for VK_EXT_transform_feedback

### PR DESCRIPTION
**Pull request by dneto0**
The validator now allows capabilities GeometryStreams and
TransformFeedback.
See https://github.com/KhronosGroup/SPIRV-Tools/issues/2084

### CODE REVIEW

**Comment by dneto0** [comment]
I'm working on the Windows build break:  https://github.com/KhronosGroup/SPIRV-Tools/pull/2102

**Comment by dneto0** [comment]
I'm working on the Windows build break: KhronosGroup/SPIRV-Tools#2102

**Comment by johnkslang** [comment]
There seems to be a problem with the precompiled headers, did that change or become inconsistent somehow?

**Comment by johnkslang** [comment]
This was apparently subsumed by #1598, so closing.

**Pull request closed without merging**
