### PR TITLE
Remove GLSLANG_WEB and GLSLANG_WEB_DEVEL

### PR DESCRIPTION
**Pull request by dj2**
This CL removes the GLSLANG_WEB and GLSLANG_WEB_DEVEL cmake build options and usage.

Issue #2958

### CODE REVIEW

**Comment by ncesario-lunarg** [comment]
@dj2 Do you happen to know if https://github.com/KhronosGroup/glslang/tree/main/glslang/OSDependent/Web is still used?

**Comment by arcady-lunarg** [comment]
@ncesario-lunarg I think that is used by the emscripten build.

**Comment by dj2** [comment]
Rebased.

**Review by arcady-lunarg — APPROVED** [review]
LGTM, thanks.

**Comment by dj2** [comment]
Looks like the bots have passed, would you be able to merge for me as I don't have permissions? Thanks.

**Pull request merged**
