### PR TITLE
fix crash in HLSL frontend

### PR DESCRIPTION
**Pull request by Try**
fix crash, when converting HLSL return of hull shader into spirv/glsl like arrayed output.

#fixed 2914

### CODE REVIEW

**Comment by greg-lunarg** [comment]
I think this change is fine and we just need to fix the failing test hlsl.emptystructreturn.frag. This can be done by building glslangtests.exe and running it with --update-mode enabled. Then commit the new *.out to your branch.

**Comment by Try** [comment]
Hi!
It seems patch requires more work: with slightly updated example, now it's crashes in `HlslParseContext::flatten`, when processing `gl_InvocationID` member of `stage_input`.

**Comment by arcady-lunarg** [comment]
I've rebased your PR on main and made a small change, with which the tests appear to pass and the crash no longer reproduces on your example.

**Review by greg-lunarg — APPROVED** [review]
LGTM

**Pull request merged**
