### PR TITLE
For bug #2580: sparseTextureGatherOffsetsARB should only take constant offsets

### PR DESCRIPTION
**Pull request by pmistryNV**

### CODE REVIEW

**Comment by pmistryNV** [comment]
@greg-lunarg please review

**Review by greg-lunarg — CHANGES_REQUESTED** [review]
Generally looks good. Could you add an erroneous sparseTextureGatherOffsetsARB call with non-constant offset to Test/vulkan.frag to make sure the error message works?

**Comment by pmistryNV** [comment]
> Generally looks good. Could you add an erroneous sparseTextureGatherOffsetsARB call with non-constant offset to Test/vulkan.frag to make sure the error message works?

@greg-lunarg this is a GLSL extension, so this should not be added to a vulkan test case. I can add a negative and positive test to 450.frag. Let me know if that would be fine.

**Comment by greg-lunarg** [comment]
> I can add a negative and positive test to 450.frag. Let me know if that would be fine.

Yes, thanks!

**Comment by pmistryNV** [comment]
> > I can add a negative and positive test to 450.frag. Let me know if that would be fine.
> 
> Yes, thanks!

Updated changes include changes now in 450.frag, please review

**Pull request merged**
