### PR TITLE
HLSL: handle clip/cull distance array semantic matching

### PR DESCRIPTION
**Pull request by LoopDawg**
In HLSL, there are three (TODO: sanity verification from HLSL expert) dimensions of clip and cull distance values:

  * The semantic's value N, ala SV_ClipDistanceN.
  * The array demension, if the value is an array.
  * The vector element, if the value is a vector or array of vectors.

In SPIR-V, clip and cull distance are arrays of scalar floats, always.

This PR currently ignores the semantic N axis entirely, which is probably incorrect, and handles the other two axes by sequentially copying each vector element of each array member into sequential floats in the output array.  This will handle some subset of the possible situations.  It will not handle N &gt; 0 in the semantic.  That will happen in a dedicated PR.

The relative priority of the vector and array dimensions are unspecified in documentation.  This is an educated guess (this order makes some sense).  It can be altered if need be.  In any case, the defect cases do not depend on that order.

Fixes: #946

### CODE REVIEW

**Comment by xxxbxxx** [comment]
I also did a patch to solve part of this problem (the vector float4 clipdist).
But it's more of a hack, since I don't quite grasp the general design of glslang:
https://github.com/xxxbxxx/glslang/commit/ab4ee35c455a41efc22b13c1d92aa434f4a67cc8

I'll give a spin to your patch and see how it behaves on my test.

**Comment by LoopDawg** [comment]
> I'll give a spin to your patch and see how it behaves on my test.

OK, thanks @xxxbxxx - appreciated.  Note that at the moment it may not support having these cases inside mixed interface structures of builtins and user variables.  I'll test that tomorrow and fix it if it's broken.

**Comment by xxxbxxx** [comment]
yeah, looks like it doesn't copies all four values. 
Looks like it doesn't get to call assignClipCullDistance() in the "// Output copies" loop.

**Comment by LoopDawg** [comment]
OK thanks - that's for a case with the clipdistance in a structure?  I'll get that working and amend the PR.

**Comment by xxxbxxx** [comment]
> that's for a case with the clipdistance in a structure?
indeed.
https://github.com/xxxbxxx/glslang/blob/master/Test/hlsl.clipdistance.vert

**Comment by xxxbxxx** [comment]
> @xxxbxxx - I believe this should handle your case now. I added two test cases of similar form.

it does, thanks.

**Pull request merged**
