### PR TITLE
Implement the extension GL_EXT_spirv_intrinsics

### PR DESCRIPTION
**Pull request by amdrexu**
- Add support of SPIR-V execution mode qualifiers.
- Add support of SPIR-V storage class qualifier.
- Add support of SPIR-V decorate qualifiers.
- Add support of SPIR-V type specifier.
- Add support of SPIR-V intruction qualifiers.
- Add support of spirv_by_reference/spirv_literal parameter qualifier.
- Add shader stage macros introduced by this extension.

### CODE REVIEW

**Comment by amdrexu** [comment]
This change is to implement the extension https://github.com/KhronosGroup/GLSL/pull/157

**Comment by greg-lunarg** [comment]
Please let me know when you are done and ready for review.

**Comment by greg-lunarg** [comment]
Re the CI-ubuntu-clang-gn failure, make sure you add any new files to BUILD.gn.

**Comment by amdrexu** [comment]
> Re the CI-ubuntu-clang-gn failure, make sure you add any new non-test source files to BUILD.gn.

Thank you. I did forget to do this.

**Comment by amdrexu** [comment]
@greg-lunarg I couldn't load the webpage to check what was wrong in the fail job. Only this job `CI-ubuntu-clang-gn` fails. Could you help to check it and tell me the details. I think I have follow your previous suggestions and have no idea about what is still missing.

**Comment by greg-lunarg** [comment]
Yeah. For reason that link is often broken. I will dig into it...

**Comment by greg-lunarg** [comment]
Please see this link:

https://source.cloud.google.com/results/invocations/13c1a60e-435d-4a2c-a37d-56d471ba4411/targets

**Comment by amdrexu** [comment]
@greg-lunarg I found the root cause and fix it now. Thanks for providing this info to me.

**Comment by greg-lunarg** [comment]
Another compilation problem:

https://source.cloud.google.com/results/invocations/3210e945-7f84-4fd3-aedd-a0fa48973269/targets

**Comment by amdrexu** [comment]
I fix it now. This change is somewhat large. If there are issues, I will continue to fix them. Once again, thanks for your patience and help.

**Comment by greg-lunarg** [comment]
I have one other larger task to finish and then will get to this. Sorry for the delay!

**Comment by amdrexu** [comment]
@greg-lunarg I rebase this PR. Thanks.

**Review by greg-lunarg — APPROVED** [review]
LGTM. Thanks for the work!

**Comment by greg-lunarg** [comment]
And sorry about making you rebase!

**Pull request merged**
