### PR TITLE
Atomic memory function can only be used for shader storage block member or shared variable.

### PR DESCRIPTION
**Pull request by ZhiqianXia**
The glsl spec says:_A shader will fail to compile if the value passed to the mem argument of an atomic memory function does not
correspond to a buffer or shared variable._

**shader**:
```
#version 320 es
layout(local_size_x = 1) in;
buffer coherent Buffer { int x; };
int y;
void main() {
  atomicAdd(x, 1);
  atomicAdd(y, 2);
}
```
**issue:**
https://github.com/KhronosGroup/glslang/issues/2642

**ref:**
https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf (8.11. Atomic Memory Functions)

### CODE REVIEW

**Comment by ZhiqianXia** [comment]
@greg-lunarg Hi , greg. Do you know how to use glslangvalidator to generate the AST ? The CI tell me the  Test/baseResults/atomicAdd.comp.out didn't match to the expected. I used the following cmd :
`glslangValidator.exe -i -l -S atomicAdd.comp`

Is there anything wrong ? Thank you.
refs: 
 https://travis-ci.com/github/KhronosGroup/glslang/jobs/505203304

**Comment by greg-lunarg** [comment]
The easiest way to update the baseResults files is by running glslangtests.exe --update-mode. Then commit the changed results files.

**Comment by ZhiqianXia** [comment]
@greg-lunarg thanks to your suggestion.😀

**Comment by ZhiqianXia** [comment]
@greg-lunarg could you help me to merge the pr into upstream ? by the way, when i builded the upstream code, I found that there are 75 glsangtest fails on upstream code.

**Comment by ZhiqianXia** [comment]
Hi Greg , Could you merged the commit into master ? @greg-lunarg

**Comment by alegal-arm** [comment]
This PR broke Vulkan CTS.
The example of a failing shader:

```
#version 450 core
#pragma use_vulkan_memory_model
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_shuffle : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_EXT_buffer_reference : enable
// DIM/NUM_WORKGROUP_EACH_DIM overriden by spec constants
layout(constant_id = 0) const int DIM = 1;
layout(constant_id = 1) const int NUM_WORKGROUP_EACH_DIM = 1;
shared bool sharedSkip;
layout(local_size_x_id = 0, local_size_y_id = 0, local_size_z = 1) in;
layout(buffer_reference) buffer PayloadRef { uint x[]; };
layout(buffer_reference) buffer GuardRef { uint x[]; };
layout(set=0, binding=2) buffer Fail { uint x[]; } fail;
layout (push_constant, std430) uniform PC {
   layout(offset = 0) PayloadRef payloadref;
layout(offset = 8) GuardRef guard;
};
void main()
{
   bool pass = true;
   bool skip = false;
   sharedSkip = false;
   nonprivate PayloadRef payload = payloadref;
   ivec2 globalId          = ivec2(gl_GlobalInvocationID.xy);
   ivec2 partnerGlobalId   = ivec2(DIM*NUM_WORKGROUP_EACH_DIM-1) - ivec2(gl_GlobalInvocationID.xy);
   uint bufferCoord        = globalId.y * DIM*NUM_WORKGROUP_EACH_DIM + globalId.x;
   uint partnerBufferCoord = partnerGlobalId.y * DIM*NUM_WORKGROUP_EACH_DIM + partnerGlobalId.x;
   ivec2 imageCoord        = globalId;
   ivec2 partnerImageCoord = partnerGlobalId;
   ivec2 globalId00          = ivec2(DIM) * ivec2(gl_WorkGroupID.xy);
   ivec2 partnerGlobalId00   = ivec2(DIM) * (ivec2(NUM_WORKGROUP_EACH_DIM-1) - ivec2(gl_WorkGroupID.xy));
   uint bufferCoord00        = globalId00.y * DIM*NUM_WORKGROUP_EACH_DIM + globalId00.x;
   uint partnerBufferCoord00 = partnerGlobalId00.y * DIM*NUM_WORKGROUP_EACH_DIM + partnerGlobalId00.x;
   ivec2 imageCoord00        = globalId00;
   ivec2 partnerImageCoord00 = partnerGlobalId00;
   payload.x[bufferCoord] = bufferCoord + (payload.x[partnerBufferCoord]>>31);
   controlBarrier(gl_ScopeWorkgroup, gl_ScopeWorkgroup, gl_StorageSemanticsBuffer | gl_StorageSemanticsShared, gl_SemanticsAcquireRelease | gl_SemanticsMakeAvailable);
   if (all(equal(gl_LocalInvocationID.xy, ivec2(0,0)))) {
       atomicStore(guard.x[bufferCoord], uint(1u), gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsRelease | gl_SemanticsMakeAvailable);
       skip = atomicLoad(guard.x[partnerBufferCoord00], gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsAcquire | gl_SemanticsMakeVisible) == 0;
       sharedSkip = skip;
   }
   controlBarrier(gl_ScopeWorkgroup, gl_ScopeWorkgroup, gl_StorageSemanticsBuffer | gl_StorageSemanticsShared, gl_SemanticsAcquireRelease | gl_SemanticsMakeVisible);
   skip = sharedSkip;
   uint r = payload.x[partnerBufferCoord];
   if (!skip && r != uint(partnerBufferCoord)) { fail.x[bufferCoord] = 1; }
}
```

The log:
```
ERROR: 0:42: 'atomicStore' : Atomic memory function can only be used for shader storage block member or shared variable. 
```

As far as I see, guard.x[partnerBufferCoord00] points to a shader storage block member

**Comment by greg-lunarg** [comment]
@alegal-arm Putting the following shader in t.comp and running `glslangValidator.exe --target-env vulkan1.2 -o t.comp.spv t.comp`, I am not seeing an error. Can you suggest a command line that reveals the problem you are seeing?

**Comment by greg-lunarg** [comment]
This PR is clearly causing a regression in CTS, so I am going to revert for the moment.

@ZhiqianXia When @alegal-arm is able to give a command line, can you investigate?

**Comment by greg-lunarg** [comment]
@alegal-arm Never mind my request above. I had a stale glslangValidator. I can recreate the error.

@ZhiqianXia Can you fix this latest shader?

**Comment by ZhiqianXia** [comment]
@alegal-arm Sorry about that. @greg-lunarg I'll fix it as soon as possible.

**Comment by greg-lunarg** [comment]
I have not completely verified this, but here is what I suspect:

The variable "guard" is a buffer_reference (aka pointer) that points into storage buffer space. Any dereference through "guard" is thus legal for atomics.

Though it points into storage buffer space , the variable "guard" itself lives in Uniform. I suspect your test sees the Uniform and gives an error. You will also need to allow for variables that are a buffer_reference, or dereferences through them.

I think buffer_reference is a qualifier.

**Pull request merged**
