### PR TITLE
Fix incorrect extension dependency for Modf

### PR DESCRIPTION
**Pull request by eilswe-arm**
See issue for details #3814

### CODE REVIEW

**Comment by jeremy-lunarg** [comment]
Can you submit a test that exercises this code path? As it stands, none of the existing tests are affected.

**Comment by jeremy-lunarg** [comment]
It seems this condition should be unnecessary. If we have a half-precision operand, then wouldn't this capability have already been generated? Can't we just eliminate these two lines?

**Comment by eilswe-arm** [comment]
After a look, I agree that the check is unnecessary, I removed it from the patch. I guess this removes the need for a test? There is already a test for 16bit float modf in glslang/Test/spv.float16.frag.

**Review by jeremy-lunarg — APPROVED** [review]
LGTM. Thanks for the fix.

**Pull request merged**
