### PR TITLE
Produce different names for files in debug builds on MSVC

### PR DESCRIPTION
**Pull request by jherico**
Fix for #310

### CODE REVIEW

**Comment by johnkslang** [comment]
Which file names are effected?

**Comment by jherico** [comment]
The lib file artifacts that are installed, specifically `glslang.lib`, `HLSL.lib`, `OGLCompiler.lib`, `OSDependent.lib`, and `SPIRV.lib`.  With this PR, if you do a debug build in Visual Studio, each file gets a `d` suffix, like so `glslangd.lib`, `HLSLd.lib`, etc...

**Comment by jherico** [comment]
An alternative would be to modify the INSTALL targets so that the debug versions of the libraries are placed in a separate directory, but I don't know how to do that off the top of my head.  using a `d` suffix is pretty common for this kind of thing in my experience.

**Comment by johnkslang** [comment]
Okay, so this will impact all downstream uses that link a debug executable based on the existing names.

**Comment by jherico** [comment]
Potentially, but as it stands, anyone using cmake to create and build the MSVC version of this project would presumably already be having issues since the debug and release versions overwrite one another in the install directory.  However, if someone is already working around that issue or has another build pipeline that uses MSVC, requires the debug libs as well as the release libs and has hardcoded the names for them somewhere, yes they would have to update something.

**Comment by johnkslang** [comment]
So, downstream users that want debug libraries will need to modify their build system to pick them up.  Otherwise, they'll get the non-debug libraries no matter how glslang was built.  Yes?  I think that's okay, just giving a fair warning time.

**Pull request merged**
