### PR TITLE
Don't force CMAKE_DEBUG_POSTFIX if forced by the user

### PR DESCRIPTION
**Pull request by robUx4**
This allows building in debug mode and use the library as if it was a release build.

(the line at the end was added by the GitHub editor)

### CODE REVIEW

**Review by jeremy-lunarg — CHANGES_REQUESTED** [review]
We used to cache this variable, but it caused another [issue](https://github.com/KhronosGroup/glslang/issues/1540).

**Comment by robUx4** [comment]
Right now I have the opposite issue. I set `CMAKE_DEBUG_POSTFIX` globally but glslang sets it back to its own. The other way would be to wrap around a `if(NOT DEFINED CMAKE_DEBUG_POSTFIX)` block.

**Comment by jeremy-lunarg** [comment]
One suggestion was to use `set_target_properties`. Would that work?

**Comment by jeremy-lunarg** [comment]
Closing this for now. Please feel to reopen if you find a better solution. Thanks.

**Pull request closed without merging**
