### PR TITLE
Remove install to the SPIRV/ folder.

### LINKED ISSUE #1964: Remove deprecated install path for SPIRV/ folder
With #1963 we are installing the SPIRV/ folder into both `CMAKE_INSTALL_PREFIX/SPIRV` and `CMAKE_INSTALL_PREFIX/glslang/SPIRV`. This was to fix #1959  which broken when 7b0e236 was committed which moved the `SPIRV` folder into the `glslang` subfolder.

This is a tracking bug to remove the deprecated `CMAKE_INSTALL_PREFIX/SPIRV` installation. The plan of record is to land #1963, then update the `README.md` with a deprecation note and a 6 month lead time.  This bug will stay open during that time if folks have issues with the deprecation, please comment here. We will be installing to both `SPIRV` and `glslang/SPIRV` during the deprecation period to allow applications to migrate.

At that point, we will stop installing headers to the `CMAKE_INSTALL_PREFIX/SPIRV` folder.

### PR DESCRIPTION
**Pull request by dj2**
This CL updates the build scripts to only install to glslang/SPIRV
instead of also installing to the SPIRV/ folder. The deprecation notice
is also removed.

Note, this may cause downstream build issues if include directories have
not been updated

Fixes #1964 #2216

### CODE REVIEW

**Comment by dj2** [comment]
Could someone using GLSLang through the install path and using the `GlslangToSpv.h` header, please verify this is OK with your system?

**Comment by dj2** [comment]
I believe the answer to my concern about build paths is, if you care about making them the same, in CMake you'd just add the parent of the `glslang` folder which makes the build paths the same between cmake and system.

**Comment by johnkslang** [comment]
Some of these headers are not an "interface" to glslang, and should never have been installed as such.

**Comment by johnkslang** [comment]
Due to the amount of energy and presumption around the history of this, I thought it worth documenting, as it is an accumulation of changes that each on it's own that does not seem so bad:

- @johnkslang: 2015: Created HEADERS as the private SPIR-V headers needed to build glslang, nothing public, but had a `spirv.hpp` in the list
- @dneto0: Apr 14, 2016: Created SPIRV-Headers `include/spirv/1.0/spirv.hpp` for public use of SPIR-V.
- userA: Jan 29, 2017: added installing glslang HEADERS to the local path `include/SPIRV`
- userB: Apr 28, 2018, changed `include/SPIRV` to `${CMAKE_INSTALL_INCLUDEDIR}/SPIRV/`
- helperC: Oct 3, 2019: moved `${CMAKE_INSTALL_INCLUDEDIR}/SPIRV/`  to `${CMAKE_INSTALL_INCLUDEDIR}/glslang/SPIRV/`, breaking downstream builds

Apparently, people wanted to use glslang's copy of `spirv.hpp` as the public header for doing SPIR-V work, and migrated it there instead of using SPIRV-Headers. Subsequently, a reasonable amount of complaints about glslang "adding copies" and "breaking compatibility", etc. were unintended consequences of the above sequence.

(It still seems strange to me that building glslang libraries should involve installing headers in prominent public locations.)

**Pull request merged**
