### PR TITLE
Always enable the generation of OpDebugBasicType for bool type

### PR DESCRIPTION
**Pull request by chaocNV**
Fixing issue https://github.com/KhronosGroup/glslang/issues/3376

### CODE REVIEW

**Review by arcady-lunarg — CHANGES_REQUESTED** [review]
This doesn't seem right, if you look at the changes in the test results it's generating the debug type multiple times and massively increasing the number of IDs used. You need to make sure the bool debug type only gets emitted once.

**Comment by chaocNV** [comment]
> This doesn't seem right, if you look at the changes in the test results it's generating the debug type multiple times and massively increasing the number of IDs used. You need to make sure the bool debug type only gets emitted once.

Fixed. Could you help merge?

**Comment by chaocNV** [comment]
A friendly pain on review/merge @ncesario-lunarg @arcady-lunarg

**Review by arcady-lunarg — APPROVED** [review]
What was putting me off was the fact that your change makes the SPIR-V smaller, but it is actually because the current version of the code apparently repeatedly generates OpDebugTypeBasic for bool, whereas after your change it is only generated once. So your change is making things more correct.

**Pull request merged**
