### PR TITLE
Automapping opengl location

### PR DESCRIPTION
**Pull request by Roy-AMD**
# This change for OpenGL shader in/out symbol and uniform symbol location Auto mapping.  [issue]#1747 
## 1. Background.
In OpenGL shader, user are not required to declare location explicit. so we need do a auto slot allocate in mapIO. 
In old implementation, when declare a implicit location symbol, resolver will only make a location self grow, and it will be reset at add stage. That makes it‘s difficult for us to refer to the declare of in/out between two shader stage and refer to the uniform in other shader stage.

relative issue : [GLSL vertex attribute overlap](https://github.com/KhronosGroup/glslang/issues/1747)
## 2. New Implementation.
To reduce the complexity of new code and reduce the impact on OpenGL ES and Vulcan shader compiler.
We base the code on `TDefaultIoResolverBaseand `and `TIoMapper`, and derived `TDefaultGlslIoResolver`, `TGlslIoMapper `to detach logic.
In new Implementation, we adjusted the interface of the `TIoMapResolver `and use entryInfo as param to help get more information, move the resolver to then end of `mapIO `in function `doMap`, and add two new step —— slot collect(`TSlotCollector`) and symbol validater(`TSymbolValidater`). At slot collect we collect symbol info and compute the free slot. At symbol validater, we check [symbol](url) type is matched. after that all, wo do resolver and set traverser.
## 3. Subsequent
Now, the test of OpenGL shader in/out mapper is missing, need add more test in glslangtest. I want it can be a option on glslangValidor. if it's possiable, we will do this two task next.

### CODE REVIEW

**Comment by Roy-AMD** [comment]
Hi @johnkslang 
I refine the code and made a cleaner pull request, I hoped  it more easily to review.
Thanks
Ruoyu

**Comment by johnkslang** [comment]
Thank you.  I had already partially reviewed the first one, but I don't mind switching to this one.

It is a very large change/addition.  Can you identify what existing functionality might change (or is at risk of changing if there is a bug)?

**Comment by Roy-AMD** [comment]
Hi @johnkslang 
Thank you very much, 
This change changes the interface and data structure, Although I want to keep all the existing functionality remain, there may still be some small issue. I have used gtest to check and fixed two issues, so I think there may have mistake, but the risk is low.
Thanks
Ruoyu

**Comment by Roy-AMD** [comment]
Hi @johnkslang ,
Is here any update or question?
if you need I do something to speed up code reviews, please let me know.
Thanks
Ruoyu

**Comment by Roy-AMD** [comment]
Hi @johnkslang，
We have some new change base on this PR need submit, can you speed up code review ?
Thanks
Ruoyu

**Comment by johnkslang** [comment]
Yes, will do that today or tomorrow.

**Comment by johnkslang** [comment]
This changes a publicly exposed interface.  Who is at risk of breaking from changing that interface?

Can it be done in a backward compatible way?  Wrapper functions, default parameters, or it really is compatible and I don't see it?

**Comment by Roy-AMD** [comment]
Hi @johnkslang ,

I think no one will have risk of changing that interface, Although the interface has changed, but it's easy to do compatibility at client,  if they use default resolver, they even need do nothing.
And it's not a good idea to done in a backward compatible at TIoMapResolver, The new interface just helps us deliver more information and enriches the extensibility of the class. It does not bring about two distinct ways of working. so, If we make a interface backward compatible, it would reduce the readability of the code and bring a lot of redundant code, which is not a good choice.

Thanks
Ruoyu

**Comment by Roy-AMD** [comment]
Hi @johnkslang 
Can we merge this code now?
Thanks
Ruoyu

**Comment by johnkslang** [comment]
It seems unstable WRT location numbers in the tests.

Reverting.

**Comment by johnkslang** [comment]
See logs for test failures in the commit to master.

**Comment by johnkslang** [comment]
Also see #1850 for an additional thing to fix.

**Pull request merged**
