### PR TITLE
Improve gtest infra and add include file test

### PR DESCRIPTION
**Pull request by qingyuanzNV**
- Add includer to gtest for include file tests.
- Move some tests from legacy script to gtest.
- Turn on debug info flag for non-semantic debug test.

This is the infra part of change from https://github.com/KhronosGroup/glslang/pull/3513

### CODE REVIEW

**Comment by arcady-lunarg** [comment]
Part of this is addressed by #3375 which I am going to actually merge shortly because I finally figured out the line endings issue, so you're going to have to rebase this, but you also should have fewer CI problems.

**Comment by qingyuanzNV** [comment]
Okay. I'll rebase after that one is merged.

**Comment by arcady-lunarg** [comment]
The other change has been merged now.

**Comment by arcady-lunarg** [comment]
Looks like more line ending problems, ugh.

**Comment by arcady-lunarg** [comment]
Looks like the failures are line ending issues, make sure you're adding both the test file and the result file with line endings that are consistent between the two of them, I think probably unix line endings would work better in this case.

**Comment by qingyuanzNV** [comment]
Yeah, I guessed the same. I'm quite busy with some other deadline recently and I'll get back to this tomorrow.

**Comment by qingyuanzNV** [comment]
@arcady-lunarg sorry to get back to this late. I have addressed the line-ending issue for all test files. Please help review and squash with the following commit message.

```
Improve gtest infra for includer support and add include file test
- Add includer to gtest for include file tests.
- Move some tests from legacy script to gtest.
```

**Comment by arcady-lunarg** [comment]
@qingyuanzNV I think you need to move the test back to the runtests script, it is there because it gets run twice with different command line options, for one thing one version is run with `-G` and the other with `-V`.

**Comment by arcady-lunarg** [comment]
I've rebased the branch and pushed a commit to undo the moving of that one test from runtests to gtest. Otherwise I think the changes are good.

**Review by arcady-lunarg — APPROVED** [review]

**Pull request merged**
