### PR TITLE
HLSL: Adding cast support for unsigned int (uint) for Load method, also upd…

### PR DESCRIPTION
**Pull request by dankbaker**
…ating tests to test for it.

Problem: Load method wasn't accepting uint inputs, because no entry in the symbol tables.

Added entries in symbol tables and also updated tests to check that loads from UINT are supported.

### CODE REVIEW

**Comment by johnkslang** [comment]
Question: Are uint this supposed to be accepted through implicit conversions or with additional intrinsics?

@steve-lunarg any input on this?

Thanks.

**Comment by dankbaker** [comment]
The implicit conversion currently didn't accept it, though that would work just as well

**Comment by johnkslang** [comment]
So, the generic selection algorithm for signature selection under implicit conversion went in a few days ago, and the specialization for HLSL is on its way (currently at GLSL #version 400 level, and just hours from being what we've been jointly designing in the other issues for HLSL).

In the meantime, master is at GLSL #version < 400 levels, which allow int -> uint, but not uint -> int.

Having said that, if the "right" thing is to have uint intrinsics, rather than int intrinsics under uint->int conversion, I understand the PR.  Such things can matter, as far as whether or not an ambiguous selection is found or not, so it is worthwhile knowing which way is correct.

**Comment by steve-lunarg** [comment]
Documentation mentions only int, which at least for the offset parameter makes some intuitive sense (no reason to restrict offsets to non-negative values).  Without a reason to the contrary, the evidence I know of seems to point to implicit conversions.

**Comment by dankbaker** [comment]
It depends what you want the SPIRV to be. If it's an implicit conversion, then you end up with a cast in the SPIRV, right? That seams a little strange to me because .Load methods are basically undefined AFAIK with negative numbers as their index, or it may clamp to 0.

HLSL itself would done an implicit conversion, however that's a bit misleading because it would also have not passed on any sort of conversion down the stream, so you can't quite compare the two.

**Comment by johnkslang** [comment]
> It depends what you want the SPIRV to be. If it's an implicit conversion, then you end up with a cast in the SPIRV, right? 

A conversion from uint -> int is a bitcast, not an actual operation.

>  That seams a little strange to me because .Load methods are basically undefined AFAIK with negative numbers as their index, or it may clamp to 0.

The top bit is set whether or not a bitcast or native intrinsic was involved, so I don't follow this part.

>  it would also have not passed on any sort of conversion down the stream

I don't think there is any conversion to pass downstream, as the bitcast is just a type-changing device, it does not translate to any executable code.

**Comment by johnkslang** [comment]
FYI, commit fcc0aa3b647f0943cc9d29e1426b968526e94001 was just pushed, and switches over from using the hardcoded GLSL #version 120 overloaded signature selection rules, to instead use the generic selector (as designed in issue #142).

This is currently parameterized with GLSL #version 400 rules, but is the base from which to make deltas to HLSL rules.  Adding uint->int is trivial, the smearing/truncating conversions slightly less so.  Will do these next.

**Comment by steve-lunarg** [comment]
I thought out of bounds loads were generally guaranteed to produce zeros in HLSL, rather than being undefined.  This verbiage is slightly ambiguous, but my SWAG would be that out of bounds access in the negative direction would act similarly to the positive.

> Note  When one or more of the coordinates in Location exceed the u, v, or w mipmap level dimensions of the texture, Load returns zero in all components. _Direct3D guarantees to return zero for any resource that is accessed out of bounds._

Independent of the topic above, I'm not sure what sort of guarantees SPIR-V makes in this regard.  I'll try to go research that tomorrow, unless someone knows off the top of their head.

**Comment by dankbaker** [comment]
It might produce 0s, I can't recall what happened if it was a clamp to bound or something else.

I don't have a strong opinion about it except that a uint intrinsic is probably slightly more in line with what HLSL would produce, because the implicit conversion would have created effectively a new Load method that took uint.  The argument against it is just going down the path of having tons of slightly different intrinsic definitions in the symbol table, which seems a big negative to me as that could get rather bloated.  If you're fine with the bit of extra SPIRV casting then it's fine to do it with implicit conversions.

However, I would like to keep the tests to make sure the conversions compile.

**Comment by steve-lunarg** [comment]
> However, I would like to keep the tests to make sure the conversions compile.

Yep, agreed - it seems important to have test coverage.

Some of the existing tests have ifdefed out sections meant to be enabled when implicit conversion rules are online.  They certainly don't cover all the bases though.

**Comment by johnkslang** [comment]
Okay, commit 90dd70f752645863524bb91040d5631236f0d017 now takes the next step, in allowing any basic type (bool, int, uint, float, double) to convert to any of the others.  For disambiguity, the following rules were used:

        // exact match is always better than mismatch
        // float -> double is better than any other float conversion
        // int -> uint is better than any other int conversion
        // -> float is better than -> double
        // -> int is better than -> bool
        // -> uint is better than -> int

This is a guess at HLSL, I'm totally open to having more concrete/correct rules.

I agree with @steve-lunarg about tests and @dankbaker about not losing the tests in this PR: Your choice:  You can either have me turn on (need to know where) and include (from this PR), or do your own submissions.

This change may be somewhat chaotic, as it's a pretty radical semantic change from #version 400 rules, but it must be a step down the right road, given that HLSL seems to support all directions of conversion.

**Comment by johnkslang** [comment]
Closing this one.

Would make sense to see any of these replace it though:

- just the tests
- the tests and the new intrinsics, if it is incorrect to have this work through implicit conversion

I welcome either of these with tests passing, etc., so they could be pulled. Thanks.

**Pull request closed without merging**
