### PR TITLE
Use CMake's builtin functionality for pre-compiled headers

### PR DESCRIPTION
**Pull request by ben-clayton**
`glslang_pch()` did manual mangling of the compiler flags to enable pre-compiled headers.
I couldn't get this approach to work with the `MachineIndependent` subdirectory / static lib, but fortunately CMake has added first-class support for precompiled headers in 3.16, which does work with the new static libraries.

Moved `glslang_pch()` to the other global function declarations.

`glslang_pch()` is a no-op when using CMake earlier than `3.16`.

CMake's PCH implementation does not need the `pch.cpp` files, so just remove them.

### CODE REVIEW

**Comment by ben-clayton** [comment]
Based on https://github.com/KhronosGroup/glslang/pull/2326

**Comment by johnkslang** [comment]
@jeffbolznv do you think this new way of doing PCH will work for you?

Anyone:  What versions of CMake are used on dev boxes?

Thanks.

**Comment by jeffbolznv** [comment]
I tried it with Visual Studio and didn't have any problems. It would be good if somebody tried it with ninja + MSVC, I had all sorts of problems trying to get ninja to work with PCH and eventually gave up.

**Comment by ben-clayton** [comment]
>  It would be good if somebody tried it with ninja + MSVC, I had all sorts of problems trying to get ninja to work with PCH and eventually gave up.

Yes, I believe it does.

Using the `Developer Command Prompt for VS 2019`:

```
> cd c:\src\glslang
> mkdir build
> cd build
> cmake .. -GNinja
> ninja
> dir glslang\CMakeFiles\MachineIndependent.dir
 Directory of c:\src\glslang\build\glslang\CMakeFiles\MachineIndependent.dir

08/07/2020  05:00 PM    <DIR>          .
08/07/2020  05:00 PM    <DIR>          ..
06/07/2020  07:52 PM                26 cmake_pch.cxx
08/07/2020  05:00 PM           312,520 cmake_pch.cxx.obj
08/07/2020  05:00 PM        47,382,528 cmake_pch.cxx.pch
06/07/2020  07:52 PM               154 cmake_pch.hxx
06/07/2020  07:52 PM                26 cmake_pch.hxx.cxx
08/07/2020  04:59 PM    <DIR>          Debug
08/07/2020  05:00 PM    <DIR>          HLSL
08/07/2020  05:00 PM    <DIR>          MachineIndependent
08/07/2020  05:00 PM         5,435,392 MachineIndependent.pdb
08/07/2020  04:59 PM    <DIR>          MinSizeRel
08/07/2020  04:59 PM    <DIR>          Release
08/07/2020  04:59 PM    <DIR>          RelWithDebInfo
```


The builtin CMake integration in VS 2019 by default uses ninja, without issue.

**Pull request merged**
