### PR TITLE
Add support for GL_NV_shader_noperspective_interpolation

### PR DESCRIPTION
**Pull request by ben-clayton**
Extension documentation:

https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_noperspective_interpolation.txt

### CODE REVIEW

**Comment by ben-clayton** [comment]
I haven't added any negative tests, as I'm not sure what the policy is W.R.T pre-processor enabled extensions (these depend on `NV_EXTENSIONS`.) If we simply assume they're always available, I can add them.

**Comment by johnkslang** [comment]
>  I'm not sure what the policy is W.R.T pre-processor enabled extensions (these depend on NV_EXTENSIONS

Does the following code snippet help answer this?

```
#ifdef NV_EXTENSIONS
INSTANTIATE_TEST_CASE_P(
    Glsl, CompileVulkanToSpirvTestNV,
    ::testing::ValuesIn(std::vector<std::string>({
    "spv.sampleMaskOverrideCoverage.frag",
    "spv.GeometryShaderPassthrough.geom",
    "spv.viewportArray2.vert",
    "spv.viewportArray2.tesc",
    "spv.stereoViewRendering.vert",
    "spv.stereoViewRendering.tesc",
    "spv.multiviewPerViewAttributes.vert",
    "spv.multiviewPerViewAttributes.tesc",
    "spv.atomicInt64.comp",
})),
FileNameAsCustomTestSuffix
);
#endif
```

**Comment by ben-clayton** [comment]
Added tests.
I tried adding them as a SPIR-V test, but this does not work due to the extension being a GLES extension, and there's no support for ESSL -> SPIR-V right now.

**Comment by johnkslang** [comment]
Ah, this is not about SPIR-V, so I picked an odd example.

**Comment by ben-clayton** [comment]
I just pushed one minor edit to the last CL, removing a bad comment. Ready for review.

**Pull request merged**
