### PR TITLE
The first redeclarations of gl_FragCoord must appear before any use.

### PR DESCRIPTION
**Pull request by ZhiqianXia**
fix issue https://github.com/KhronosGroup/glslang/issues/2898

### CODE REVIEW

**Comment by greg-lunarg** [comment]
I think the current failure may be transient. Resubmitting the branch should hopefully resolve it.

However, I would like to see a change as well. There should be code that checks that the second redeclaration is identical to the first. If it is not, an error should be issued to that effect. This is consistent with the spec which says: All redeclarations of
gl_FragCoord in all fragment shaders in a single program must have the same set of qualifiers.

**Comment by greg-lunarg** [comment]
In other words, the code should make sure that any redeclarations following the first redeclaration does not change anything.

**Comment by ZhiqianXia** [comment]
Hi @greg-lunarg, I found that following code , which can guarantee that "All redeclarations of
gl_FragCoord in all fragment shaders in a single program must have the same set of qualifiers."

```
            if (! builtIn && (publicType.pixelCenterInteger != intermediate.getPixelCenterInteger() ||
                              publicType.originUpperLeft != intermediate.getOriginUpperLeft()))
                error(loc, "cannot redeclare with different qualification:", "redeclaration", symbol->getName().c_str());
```

**Comment by greg-lunarg** [comment]
Great! Sorry I didn't catch that.

Can you please resubmit your branch to see if the build failure resolves? One way I do that is by doing a git commit --amend on the local branch, writing with no change and force-pushing the branch.

Thanks!

**Comment by greg-lunarg** [comment]
Here is the error that is causing the build failure. Can you please fix?:

[81/400] CXX obj/glslang_sources/ParseHelper.o
FAILED: obj/glslang_sources/ParseHelper.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/glslang_sources/ParseHelper.o.d -DENABLE_OPT=1 -DGLSLANG_OSINCLUDE_UNIX -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-5627-gf086e85e-2\" -DCOMPONENT_BUILD -DCR_SYSROOT_HASH=5f64b417e1018dcf8fcc81dc2714e0f264b9b911 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DENABLE_HLSL=1 -Igen/include -I../../External/spirv-tools/include -I../.. -Igen -I../.. -I../../External/spirv-tools/include -Wno-extra-semi -Wno-ignored-qualifiers -Wno-implicit-fallthrough -Wno-inconsistent-missing-override -Wno-missing-field-initializers -Wno-newline-eof -Wno-sign-compare -Wno-suggest-destructor-override -Wno-suggest-override -Wno-unused-variable -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -mllvm -enable-dse-memoryssa=false -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O0 -fno-omit-frame-pointer -g2 -Xclang -debug-info-kind=constructor -gsplit-dwarf -ggnu-pubnames -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Werror -Wall -Wno-unused-variable -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -Wno-conversion -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../glslang/MachineIndependent/ParseHelper.cpp -o obj/glslang_sources/ParseHelper.o
In file included from ../../glslang/MachineIndependent/ParseHelper.cpp:40:
In file included from ../../glslang/MachineIndependent/ParseHelper.h:54:
../../glslang/MachineIndependent/localintermediate.h:312:36: error: field 'originUpperLeft' will be initialized after field 'texCoordBuiltinRedeclared' [-Werror,-Wreorder-ctor]
        pixelCenterInteger(false), originUpperLeft(false),texCoordBuiltinRedeclared(false),
                                   ^
1 error generated.

**Pull request merged**
